services:
  spike_openocd_gdb:
    image: five_embeddev/examples/riscv_spike_debug_env_sim_gdb
    command: [  "--priv=m" ,"--isa=rv32imac", "-m0x8000000:0x2000,0x80000000:0x4000,0x20010000:0x6a120", "/project/build/main.elf"]
    tty: true
    volumes:
        - .:/project
        - ./src:/home/phil/github-wsl/modern-cxx/coro/riscv_baremetal/src
        - /home/phil/.local/xPacks/@xpack-dev-tools:/home/phil/.local/xPacks/@xpack-dev-tools
